version: '3'

services:
  dev:
    build: ./docker/dev
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - TERRAFORM_S3_BACKEND_BUCKET=${TERRAFORM_S3_BACKEND_BUCKET}
    tty: true
    volumes:
      - ../:/workspace
